---Create Table

CREATE TABLE   Integration.TBL_DIM_PRODUCT_NAME_LKP

(
PRODUCT_NAME_KEY INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_NUMBER INT,
PRODUCT_NAME VARCHAR(255),
PRODUCT_DESCRIPTION VARCHAR(255),
SOURCE_ID VARCHAR(50),
DATA_DATE DATE,
UPDATE_DATE DATE
)

 CREATE TABLE Integration.PRODUCT(
        PRODUCT_KEY INT IDENTITY(1,1) PRIMARY KEY,
        PRODUCT_NUMBER INT NULL,
        PRODUCT_NAME VARCHAR(50) NULL,
        BASE_PRODUCT_NUMBER INT NULL,
        PRODUCT_COLOR_CODE INT NULL,
        PRODUCT_SIZE_CODE INT NULL,
        PRODUCT_BRAND_CODE INT NULL,
        PRODUCTION_COST DECIMAL(19,2) NULL,
        INTRODUCTION_DATE DATE NULL,
        DISCONTINUED_DATE DATE NULL,
        SOURCE_ID VARCHAR(255) NULL,
        DATA_DATE DATE NULL,
        UPDATE_DATE DATE NULL
)

CREATE TABLE Integration.TBL_DIM_COUNTRY_LKP
(
COUNTRY_KEY INT IDENTITY(1,1) PRIMARY KEY,
COUNTRY_CODE INT,
COUNTRY_ID VARCHAR(100),
COUNTRY_NAME VARCHAR(100),
SOURCE_ID VARCHAR(50),
DATA_DATE DATE,
UPDATE_DATE DATE

)

CREATE TABLE Integration.TBL_DIM_ORDER (
    ORDER_KEY INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_DETAIL_CODE INT NOT NULL,
    ORDER_NUMBER INT NOT NULL,
    BRANCH_CODE NVARCHAR(50),
    WAREHOUSE_BRANCH_CODE NVARCHAR(50),
    COUNTRY_CODE NVARCHAR(50),
    WAREHOUSE_CITY NVARCHAR(100),
    SHIP_DATE DATE,
    QUANTITY INT,
    UNIT_COST DECIMAL(18,2),
    UNIT_PRICE DECIMAL(18,2),
    UNIT_SALE_PRICE DECIMAL(18,2),
    ORDER_DATE DATE,
    ORDER_CLOSE_DATE DATE,
    SOURCE_ID VARCHAR(50),
    DATA_DATE DATE,
    UPDATE_DATE DATE,
    BEGIN_EFFECTIVE_DATE DATE,
    END_EFFECTIVE_DATE DATE,
    VERSION_NUM INT,
    CHANGE_INFO CHAR(1)
);


CREATE TABLE Integration.TBL_DIM_RETAILER_LKP

(
RETAILER_KEY INT IDENTITY(1,1) PRIMARY KEY,
RETAILER_NAME VARCHAR(50),
RETAILER_SITE_CODE INT,
RETAILER_CONTACT_CODE INT,
SOURCE_ID VARCHAR(50),
DATA_DATE DATE,
UPDATE_DATE DATE
)

CREATE TABLE Integration.TBL_DIM_RETURN_REASON_LKP
(
RETURN_REASON_KEY INT IDENTITY(1,1) PRIMARY KEY,
RETURN_REASON_CODE INT,
RETURN_REASON_DESC VARCHAR(255),
SOURCE_ID VARCHAR(100),
DATA_DATE DATE,
UPDATE_DATE DATE
)

CREATE TABLE Integration.TBL_DIM_WAREHOUSE_LKP(
WAREHOUSE_KEY INT IDENTITY(1,1) PRIMARY KEY,
BRANCH_CODE INT,
ADDRESS VARCHAR(100),
CITY VARCHAR(50),
POSTAL_CODE VARCHAR(100),
COUNTRY_CODE INT,
WAREHOUSE_BRANCH_CODE INT,
SOURCE_ID VARCHAR(50),
DATA_DATE DATE,
UPDATE_DATE DATE
)